### ISSUE TITLE
Allow syntax div.style()

### ISSUE THREAD

**Issue by Zantier** [414owen/Nutmeg#3]
I'm not sure that this is worth the complication it will cause in the code.

Effectively, "div" itself needs to be elified, or at least have the same functions as an elified element, i.e. div.style, div.classes, etc. And the start of these functions need to actually construct a new elified div.

div().style(): Easy. A new div is created by div().

div.style(): The new div needs to be created (or retrieved, in the case of body) within style(). I imagine div will have a reference to a constructor of either div elements or elified div elements.

**Comment by 414owen** [comment]
Will not fix. Calling functions is fine. Good call.

**Comment by 414owen** [comment]
Will not fix. Calling functions is fine. Good call.

**Comment by 414owen** [comment]
Added this feature. Eliminating brackets is good, I guess.
