### ISSUE TITLE
Add all the possible attributes to elified

### ISSUE THREAD

**Issue by 414owen** [414owen/Nutmeg#7]
I think we can loop over all the properties in an element, and create functions in elified that assign to them, before setting our custom ones.

```
for (var propName in elem) {
   elified.propName = function(val) {elem.propName = val;};
}
```

I just don't have time to experiment with it right now, so @Zantier if you want something to do today?

It might impact performance a bit, maybe run a profile on example.html before and after?

**Comment by Zantier** [comment]
200ms -> 600ms using for...in, eep. That looks through the entire prototype chain.

Tried Object.getOwnPropertyNames, but it returns an empty list. This could be combined with manually looking up the prototype chain, but then you have to decide exactly how far to look.

Computed property names seem ideal, but may not be well supported. I haven't tested it.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get#Using_a_computed_property_name

**Comment by 414owen** [comment]
Hmmm, why are you going through the prototype chain? Is this not for properties such as src, href, etc.? We don't really want to get all the functions of DOM nodes do we?

...Can we use `Object.assign(elified, node)` instead of iterating?
That might have some shiny native implementation?

**Comment by Zantier** [comment]
`for...in` automatically looks through the entire prototype chain, and `Object.getOwnPropertyNames` returns an empty list for elements themselves.

`Object.assign` is no good, as it assigns the value directly, whereas we want to assign a function.

Might be best just to have `elified.prop(key, value)`, and then common properties can be added from an array of strings. Btw `attr` and `prop` are both jQuery functions, in case you misinterpret that I'm able to come up with original ideas :)

**Comment by Zantier** [comment]
I'm probably gonna try out the "computed property name" idea tonight.

**Comment by 414owen** [comment]
It's an ECMAScript6 feature by the looks of it... I doubt it will form in many (or any) browsers.

Okay, here's a thought:
Instead of wrapping a DOM node with elified, we return the actual node, but with added Nutmeg goodness, aka. we add our functions to the node. That way, we don't have to create functions on what we return to edit node properties.
We'd obviously have to avoid existing property names, so instead of `div().style(mystyle)` we'd have to make it `div().stl(mystyle)` or something instead.

Also we'd be sacrificing the syntax `div().style(mystyle)(div())`, because we can't make the DOM node callable.

**Comment by Zantier** [comment]
But ES6 is shiny!!!  ....yeah, you're right.

Adding directly to the DOM crossed my mind. Maybe...
